# Generated by Django 3.1.7 on 2021-03-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_card_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='order_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
