# Generated by Django 3.1.7 on 2021-03-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash')], default='Cash', max_length=20),
        ),
    ]
