# Generated by Django 3.1.7 on 2021-03-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('card', 'card'), ('cash', 'cash')], default='cash', max_length=20),
        ),
    ]
