# Generated by Django 3.1.7 on 2021-03-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210322_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('sale', models.FloatField(default=0.1)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'active'), ('dead', 'dead')], default='active', max_length=10)),
            ],
        ),
    ]
