# Generated by Django 3.1.7 on 2021-03-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210317_2057'),
        ('order', '0010_auto_20210322_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='meal',
        ),
        migrations.AddField(
            model_name='order',
            name='meal',
            field=models.ManyToManyField(to='api.Meal'),
        ),
    ]
